# Copyright (C) 2025 ArmaVita LLC
# SPDX-License-Identifier: AGPL-3.0-only

import ast
from pathlib import Path


def _tool_signature_map() -> dict[str, list[str]]:
    core_dir = Path(__file__).resolve().parents[1] / "src" / "armavita_meta_ads_mcp" / "core"
    signatures: dict[str, list[str]] = {}
    for path in sorted(core_dir.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.AsyncFunctionDef):
                continue
            is_tool = False
            for decorator in node.decorator_list:
                if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute):
                    if decorator.func.attr == "tool":
                        is_tool = True
                        break
            if not is_tool:
                continue
            signatures[node.name] = [arg.arg for arg in node.args.args if arg.arg != "self"]
    return signatures


def test_v1_tool_names_are_exact():
    signatures = _tool_signature_map()
    assert set(signatures) == {
        "list_ad_accounts",
        "read_ad_account",
        "list_campaigns",
        "read_campaign",
        "create_campaign",
        "update_campaign",
        "list_ad_sets",
        "read_ad_set",
        "create_ad_set",
        "update_ad_set",
        "list_ads",
        "read_ad",
        "list_ad_previews",
        "create_ad",
        "update_ad",
        "list_ad_creatives",
        "read_ad_creative",
        "create_ad_creative",
        "update_ad_creative",
        "upload_ad_image_asset",
        "read_ad_image",
        "export_ad_image_file",
        "get_instagram_actor_id",
        "search_pages",
        "list_account_pages",
        "list_insights",
        "create_report",
        "create_campaign_budget_schedule",
        "search_interests",
        "suggest_interests",
        "estimate_audience_size",
        "search_behaviors",
        "search_demographics",
        "search_geo_locations",
        "clone_campaign",
        "clone_ad_set",
        "clone_ad",
        "clone_ad_creative",
        "search_ads_archive",
        "search_web_content",
        "read_web_content",
        # audience_tools
        "list_custom_audiences",
        "read_custom_audience",
        "create_custom_audience",
        "delete_custom_audience",
        "add_users_to_audience",
        "remove_users_from_audience",
        # video_tools
        "upload_ad_video",
        "list_ad_videos",
        "read_ad_video",
        # pixel_tools
        "list_pixels",
        "read_pixel",
        # delete_tools
        "delete_campaign",
        "delete_ad_set",
        "delete_ad",
        # rule_tools
        "create_ad_rule",
        "list_ad_rules",
        "read_ad_rule",
        "update_ad_rule",
        "delete_ad_rule",
        "execute_ad_rule",
    }


def test_v1_signature_snapshot():
    signatures = _tool_signature_map()
    assert signatures == {
        "clone_ad": [
            "ad_id",
            "meta_access_token",
            "target_ad_set_id",
            "name_suffix",
            "clone_ad_creative",
            "new_creative_name",
            "new_status",
        ],
        "clone_ad_creative": [
            "ad_creative_id",
            "meta_access_token",
            "name_suffix",
            "new_primary_text",
            "new_headline",
            "new_description",
            "new_cta_type",
            "new_destination_url",
        ],
        "clone_ad_set": [
            "ad_set_id",
            "meta_access_token",
            "target_campaign_id",
            "name_suffix",
            "include_ads",
            "include_creatives",
            "new_daily_budget",
            "new_targeting",
            "new_status",
        ],
        "clone_campaign": [
            "campaign_id",
            "meta_access_token",
            "name_suffix",
            "include_ad_sets",
            "include_ads",
            "include_creatives",
            "copy_schedule",
            "new_daily_budget",
            "new_status",
        ],
        "create_ad": [
            "ad_account_id",
            "name",
            "ad_set_id",
            "ad_creative_id",
            "status",
            "bid_amount",
            "tracking_specs",
            "meta_access_token",
        ],
        "create_ad_creative": [
            "ad_account_id",
            "ad_image_hash",
            "meta_access_token",
            "name",
            "facebook_page_id",
            "link_url",
            "primary_text",
            "primary_text_variants",
            "headline_text",
            "headline_variants",
            "description_text",
            "description_variants",
            "ad_image_hashes",
            "ad_video_id",
            "thumbnail_url",
            "optimization_type",
            "dynamic_creative_spec",
            "call_to_action_type",
            "lead_form_id",
            "instagram_actor_id",
            "ad_formats",
            "asset_customization_rules",
            "carousel_cards",
        ],
        "create_ad_set": [
            "ad_account_id",
            "campaign_id",
            "name",
            "optimization_goal",
            "billing_event",
            "status",
            "daily_budget",
            "lifetime_budget",
            "targeting",
            "bid_amount",
            "bid_strategy",
            "bid_constraints",
            "start_time",
            "end_time",
            "dsa_beneficiary",
            "promoted_object",
            "destination_type",
            "is_dynamic_creative",
            "frequency_control_specs",
            "meta_access_token",
        ],
        "create_campaign": [
            "ad_account_id",
            "name",
            "objective",
            "meta_access_token",
            "status",
            "special_ad_categories",
            "daily_budget",
            "lifetime_budget",
            "buying_type",
            "bid_strategy",
            "bid_cap",
            "spend_cap",
            "campaign_budget_optimization",
            "ab_test_control_setups",
            "use_ad_set_level_budgets",
        ],
        "create_campaign_budget_schedule": [
            "campaign_id",
            "budget_value",
            "budget_value_type",
            "time_start",
            "time_end",
            "meta_access_token",
        ],
        "create_report": [
            "ad_account_id",
            "meta_access_token",
            "report_type",
            "date_range",
            "campaign_ids",
            "export_format",
            "report_name",
            "include_sections",
            "breakdowns",
            "action_breakdowns",
            "summary_action_breakdowns",
            "comparison_period",
        ],
        "estimate_audience_size": [
            "meta_access_token",
            "ad_account_id",
            "targeting",
            "optimization_goal",
            "interest_list",
            "interest_fbid_list",
        ],
        "export_ad_image_file": ["ad_id", "meta_access_token", "output_dir"],
        "get_instagram_actor_id": ["facebook_page_id", "meta_access_token"],
        "list_account_pages": ["ad_account_id", "meta_access_token"],
        "list_ad_accounts": ["meta_access_token", "meta_user_id", "page_size", "page_cursor"],
        "list_ad_creatives": ["ad_id", "meta_access_token", "page_cursor"],
        "list_ad_previews": ["ad_id", "meta_access_token", "ad_format", "locale", "render_type", "width", "height"],
        "list_ad_sets": ["ad_account_id", "meta_access_token", "page_size", "campaign_id", "page_cursor"],
        "list_ads": ["ad_account_id", "meta_access_token", "page_size", "campaign_id", "ad_set_id", "page_cursor"],
        "list_campaigns": [
            "ad_account_id",
            "meta_access_token",
            "page_size",
            "status_filter",
            "objective_filter",
            "page_cursor",
        ],
        "list_insights": [
            "object_id",
            "meta_access_token",
            "date_range",
            "breakdown",
            "breakdowns",
            "action_breakdowns",
            "summary_action_breakdowns",
            "level",
            "page_size",
            "page_cursor",
            "action_attribution_windows",
            "compact",
        ],
        "read_ad": ["ad_id", "meta_access_token"],
        "read_ad_account": ["ad_account_id", "meta_access_token"],
        "read_ad_creative": ["ad_creative_id", "meta_access_token"],
        "read_ad_image": ["ad_id", "meta_access_token"],
        "read_ad_set": ["ad_set_id", "meta_access_token"],
        "read_campaign": ["campaign_id", "meta_access_token"],
        "read_web_content": ["resource_id"],
        "search_ads_archive": ["search_terms", "ad_reached_countries", "meta_access_token", "ad_type", "page_size", "page_cursor", "fields"],
        "search_behaviors": ["meta_access_token", "page_size", "page_cursor"],
        "search_demographics": ["meta_access_token", "demographic_class", "page_size", "page_cursor"],
        "search_geo_locations": ["query", "meta_access_token", "location_types", "page_size", "page_cursor"],
        "search_interests": ["query", "meta_access_token", "page_size", "page_cursor"],
        "search_pages": ["ad_account_id", "meta_access_token", "query"],
        "search_web_content": ["query", "meta_access_token"],
        "suggest_interests": ["interest_list", "meta_access_token", "page_size", "page_cursor"],
        "update_ad": ["ad_id", "status", "bid_amount", "tracking_specs", "ad_creative_id", "meta_access_token"],
        "update_ad_creative": [
            "ad_creative_id",
            "meta_access_token",
            "name",
            "primary_text",
            "primary_text_variants",
            "headline_text",
            "headline_variants",
            "description_text",
            "description_variants",
            "optimization_type",
            "dynamic_creative_spec",
            "call_to_action_type",
            "lead_form_id",
            "ad_formats",
        ],
        "update_ad_set": [
            "ad_set_id",
            "frequency_control_specs",
            "bid_strategy",
            "bid_amount",
            "bid_constraints",
            "status",
            "targeting",
            "optimization_goal",
            "daily_budget",
            "lifetime_budget",
            "is_dynamic_creative",
            "promoted_object",
            "meta_access_token",
        ],
        "update_campaign": [
            "campaign_id",
            "meta_access_token",
            "name",
            "status",
            "special_ad_categories",
            "daily_budget",
            "lifetime_budget",
            "bid_strategy",
            "bid_cap",
            "spend_cap",
            "campaign_budget_optimization",
            "objective",
            "use_ad_set_level_budgets",
        ],
        "upload_ad_image_asset": ["ad_account_id", "meta_access_token", "image_file_path", "image_source_url", "name"],
        # audience_tools
        "list_custom_audiences": ["ad_account_id", "meta_access_token", "page_size", "page_cursor"],
        "read_custom_audience": ["audience_id", "meta_access_token"],
        "create_custom_audience": [
            "ad_account_id",
            "name",
            "subtype",
            "meta_access_token",
            "description",
            "retention_days",
            "customer_file_source",
            "lookalike_spec",
            "rule",
            "pixel_id",
        ],
        "delete_custom_audience": ["audience_id", "meta_access_token"],
        "add_users_to_audience": ["audience_id", "schema", "data", "meta_access_token", "is_raw"],
        "remove_users_from_audience": ["audience_id", "schema", "data", "meta_access_token", "is_raw"],
        # video_tools
        "upload_ad_video": ["ad_account_id", "video_file_path", "title", "meta_access_token", "description"],
        "list_ad_videos": ["ad_account_id", "meta_access_token", "page_size", "page_cursor"],
        "read_ad_video": ["video_id", "meta_access_token"],
        # pixel_tools
        "list_pixels": ["ad_account_id", "meta_access_token"],
        "read_pixel": ["pixel_id", "meta_access_token"],
        # delete_tools
        "delete_campaign": ["campaign_id", "meta_access_token"],
        "delete_ad_set": ["ad_set_id", "meta_access_token"],
        "delete_ad": ["ad_id", "meta_access_token"],
        # rule_tools
        "create_ad_rule": [
            "ad_account_id",
            "name",
            "evaluation_spec",
            "execution_spec",
            "meta_access_token",
            "schedule_spec",
            "status",
        ],
        "list_ad_rules": ["ad_account_id", "meta_access_token", "page_size"],
        "read_ad_rule": ["rule_id", "meta_access_token"],
        "update_ad_rule": [
            "rule_id",
            "meta_access_token",
            "name",
            "status",
            "evaluation_spec",
            "execution_spec",
            "schedule_spec",
        ],
        "delete_ad_rule": ["rule_id", "meta_access_token"],
        "execute_ad_rule": ["rule_id", "meta_access_token"],
    }