/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
const fileMap = {
  
  "clients.baml": "client<llm> ClaudeOpus {\n  provider \"aws-bedrock\"\n  options {\n    model \"anthropic.claude-opus-4-6\"\n    region env.AWS_REGION\n  }\n}\n",
  "evaluator.baml": "class EvaluationResult {\n  score        int     @description(\"1-10 overall quality score of the generated room image\")\n  has_curtains bool    @description(\"Are curtains clearly visible on the windows?\")\n  feedback     string  @description(\"Brief reason for score\")\n}\n\nfunction EvaluateRoomImage(image: image, product_name: string) -> EvaluationResult {\n  client ClaudeOpus\n  prompt #\"\n    You are an interior design quality evaluator. Evaluate this AI-generated room image.\n\n    The image should show a room with {{ product_name }} curtains.\n\n    Score the image from 1-10 based on:\n    - Realism and photographic quality\n    - Natural integration of the curtains\n    - Lighting consistency\n    - Overall aesthetic quality\n\n    Also determine if curtains are clearly visible on the windows.\n\n    {{ ctx.output_format }}\n\n    {{ _.role(\"user\") }}\n    {{ image }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}