# Learn more about configuring your app:
# https://shopify.dev/docs/apps/tools/cli/configuration

name = "design-your-curtain"
client_id = "3fa7dbcafa45e7c47c36faff4de2672d"
application_url = "https://inanctekstil.store"
embedded = false

[auth]
redirect_urls = [
  "https://inanctekstil.store/auth/callback"
]

[webhooks]
api_version = "2025-10"
